### PR TITLE
Add substack blog post on ChatGPT profiling experiments to NOS blog.

### PR DESCRIPTION
**Pull request by outtanames**
Should match https://scottloftin.substack.com/p/lets-build-an-ml-sre-bot-with-nos

## Checks

- [ ] `make lint`: I've run `make lint` to lint the changes in this PR.
- [ ] `make test`: I've made sure the tests (`make test-cpu` or `make test`) are passing.
- Additional tests:
   - [ ] Benchmark tests (when contributing new models)
   - [ ] GPU/HW tests

### CODE REVIEW

**Comment by spillai** [comment]
Can we merge this at a later date?

**Comment by outtanames** [comment]
Might want to go ahead and reopen this and merge for a weekly post.

**Review by spillai — COMMENTED** [review]
Move to `docs/tutorials`?

**Comment by outtanames** [comment]
> Move to `docs/tutorials`?

yea which would you prefer? I think this is more of a generic blog post than a tutorial.

**Pull request merged**
